{
  "formatVersion": "1.1",
  "component": {
    "group": "com.resourceful",
    "module": "resourceful",
    "version": "1.0.4-21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourceful-1.0.4-21.jar",
          "url": "resourceful-1.0.4-21.jar",
          "size": 28282,
          "sha512": "00109829461fa5ec55090b0ac6b5809b25a171b98b60b98764505d9f2a526e9e460be30787433ad0c5a9660eaef921e5d30aac903758b55548e71a931d9eebbd",
          "sha256": "69a28bc467c0f33a331cff5aa89f610713779cbf6952c318c39a62dbb9a81a57",
          "sha1": "a93d73c028bac82fefc7102982bfdf44c17c832f",
          "md5": "0b4a234ebb3896f899e2af76dec697d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceful-1.0.4-21.jar",
          "url": "resourceful-1.0.4-21.jar",
          "size": 28282,
          "sha512": "00109829461fa5ec55090b0ac6b5809b25a171b98b60b98764505d9f2a526e9e460be30787433ad0c5a9660eaef921e5d30aac903758b55548e71a931d9eebbd",
          "sha256": "69a28bc467c0f33a331cff5aa89f610713779cbf6952c318c39a62dbb9a81a57",
          "sha1": "a93d73c028bac82fefc7102982bfdf44c17c832f",
          "md5": "0b4a234ebb3896f899e2af76dec697d6"
        }
      ]
    }
  ]
}
